#!/usr/bin/env bash

sleep 1
pkill -e -f xdg-desktop-portal-wlr
pkill -f xdg-desktop-portal
pkill -f xdg-desktop-portal-gtk
pkill -f xdg-desktop-portal-kde

/usr/libexec/xdg-desktop-portal-wlr &
/usr/libexec/xdg-desktop-portal-gtk &
/usr/libexec/xdg-desktop-portal-kde &
/usr/libexec/xdg-desktop-portal &
